- name: ensure .ssh directory exists for root user
  file: dest=/root/.ssh owner=root group=root mode=0755 state=directory
- name: put ssh keys for root user
  copy: src=./files/ssh/pub-keys dest=/root/.ssh/authorized_keys owner=root group=root mode=0600
- name: refresh apt cache
  apt: update_cache=yes
- name: install base packages
  apt: pkg={{item}} state=present
  with_items:
   - git
   - git-core
   - curl
   - strace
   - htop
   - tcpdump
   - netcat
   - screen
   - htop
   - lsof
   - vim
   - ncdu
   - rsync
   - tcpdump
